language: R
sudo: false
cache: packages
env:
  global:
    secure: YW7GskOKw64mXPj5uTiD3Od1N6OhbHm777mBJxLSxhnrass3oGEJVZAanjD+kD0XACb09rMlQEpYXdr65WW3EgoUjYaBmpNBxjl+Ijk95/+PvDnbPbyaTIiFiQkj0r+6airZvhr4L183yDRXYWpm61IKc+oVAL5xfZyEQmq4abnHb2UnhaBpZQzRh2tLErYcjFlwdru8GwJXipXFFm1hsjVZ7rAnEckG1kgj81/BVofVAcga53WDW7AoJJhdkcCyeId+8Z52w/BWq7Bsm0urAsXtXXXfDiMu63G78iPjZOT3bJf/GUXGP8s0F67U0FhLvLKO3Mztc7FS4DB6gbn343wmE4w+Z5i+Oib08Es5JoRU9Vgkp1ECJeaDvxyxnQd0uFkcxT7i7wKFL8B76rEdzzuhlSPkp4CCiSasZPvSRQzK4yNP52qPyY/trniZ00TANt/TSg/OVisbziCBhgUpUdcPaKzvU6lRkizD0esQ0UeYtIC71CbWYRQ8MQUQtQtShDhWlWhuRA+R+KKqsED6MlcHFWHNg89mGz1Tf8++W3Hrmp4f+m9u7I6BeckBxI7tLRPBAXN6iMS9JX0UgJwoJ8rcWH03xHh5V4yRtQdAScER1X7PXnbpm5Zuoh8lfVnrdo1zntIzXzLpJ4ztScN/U0hrKPzJBw5Kx5T9s5T3gfA=
